//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetPockets.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TweetPockets.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent activity.
        /// </summary>
        public static string AcitivityMenuItem {
            get {
                return ResourceManager.GetString("AcitivityMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent activity.
        /// </summary>
        public static string ActivityPageTitle {
            get {
                return ResourceManager.GetString("ActivityPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to Bookmarks.
        /// </summary>
        public static string AddedToBookmarksNotificationPattern {
            get {
                return ResourceManager.GetString("AddedToBookmarksNotificationPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksMenuItem {
            get {
                return ResourceManager.GetString("BookmarksMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksPageTitle {
            get {
                return ResourceManager.GetString("BookmarksPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d.
        /// </summary>
        public static string DaysLabel {
            get {
                return ResourceManager.GetString("DaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        public static string HoursLabel {
            get {
                return ResourceManager.GetString("HoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorited:.
        /// </summary>
        public static string LabelFavorited {
            get {
                return ResourceManager.GetString("LabelFavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quoted:.
        /// </summary>
        public static string LabelQuoted {
            get {
                return ResourceManager.GetString("LabelQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replied:.
        /// </summary>
        public static string LabelReplied {
            get {
                return ResourceManager.GetString("LabelReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retweeted:.
        /// </summary>
        public static string LabelRetweeted {
            get {
                return ResourceManager.GetString("LabelRetweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m.
        /// </summary>
        public static string MinutesLabel {
            get {
                return ResourceManager.GetString("MinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        public static string NewTweetTitle {
            get {
                return ResourceManager.GetString("NewTweetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liked &quot;{1}&quot;.
        /// </summary>
        public static string NotificationFavorited {
            get {
                return ResourceManager.GetString("NotificationFavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked &quot;{0}&quot;.
        /// </summary>
        public static string NotificationFullFavorited {
            get {
                return ResourceManager.GetString("NotificationFullFavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoted &quot;{0}&quot;.
        /// </summary>
        public static string NotificationFullQuoted {
            get {
                return ResourceManager.GetString("NotificationFullQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replied &quot;{0}&quot;.
        /// </summary>
        public static string NotificationFullReplied {
            get {
                return ResourceManager.GetString("NotificationFullReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retweeted &quot;{0}&quot;.
        /// </summary>
        public static string NotificationFullRetweeted {
            get {
                return ResourceManager.GetString("NotificationFullRetweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} quoted &quot;{1}&quot;.
        /// </summary>
        public static string NotificationQuoted {
            get {
                return ResourceManager.GetString("NotificationQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: &quot;{1}&quot;.
        /// </summary>
        public static string NotificationReplied {
            get {
                return ResourceManager.GetString("NotificationReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} retweeted &quot;{1}&quot;.
        /// </summary>
        public static string NotificationRetweeted {
            get {
                return ResourceManager.GetString("NotificationRetweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed from Bookmarks.
        /// </summary>
        public static string RemovedFromBookmarksNotificationPattern {
            get {
                return ResourceManager.GetString("RemovedFromBookmarksNotificationPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s.
        /// </summary>
        public static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string TimelineMenuItem {
            get {
                return ResourceManager.GetString("TimelineMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string TimelinePageTitle {
            get {
                return ResourceManager.GetString("TimelinePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tweet.
        /// </summary>
        public static string TweetInputFieldLabel {
            get {
                return ResourceManager.GetString("TweetInputFieldLabel", resourceCulture);
            }
        }
    }
}
